
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 38;
  public static final int INCREMENT = 31;
  public static final int CHAR = 6;
  public static final int ASTERISK = 18;
  public static final int EQUALS = 23;
  public static final int COMMENT = 50;
  public static final int LPAREN = 25;
  public static final int SEMI = 22;
  public static final int INT = 5;
  public static final int FSLASH = 21;
  public static final int MINUS = 20;
  public static final int DECREMENT = 32;
  public static final int RPAREN = 26;
  public static final int LSQR = 27;
  public static final int NOT = 33;
  public static final int AND = 16;
  public static final int LT = 37;
  public static final int OR = 17;
  public static final int COMMA = 24;
  public static final int CLASS = 2;
  public static final int NUMBERLIT = 45;
  public static final int PLUS = 19;
  public static final int IF = 10;
  public static final int ID = 44;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 12;
  public static final int PRINTLINE = 15;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int LCURLY = 29;
  public static final int MULTILINE = 51;
  public static final int NEQ = 41;
  public static final int VOID = 4;
  public static final int FLOATLIT = 48;
  public static final int EQ = 40;
  public static final int GTE = 39;
  public static final int RCURLY = 30;
  public static final int CHARLIT = 46;
  public static final int COLON = 35;
  public static final int ELSE = 9;
  public static final int LETTER = 47;
  public static final int READ = 13;
  public static final int RSQR = 28;
  public static final int FINAL = 3;
  public static final int WHILE = 11;
  public static final int FLOAT = 8;
  public static final int STRING = 49;
  public static final int QUESTION = 34;
  public static final int FALSE = 43;
  public static final int GT = 36;
  public static final int PRINT = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "FINAL",
  "VOID",
  "INT",
  "CHAR",
  "BOOLEAN",
  "FLOAT",
  "ELSE",
  "IF",
  "WHILE",
  "RETURN",
  "READ",
  "PRINT",
  "PRINTLINE",
  "AND",
  "OR",
  "ASTERISK",
  "PLUS",
  "MINUS",
  "FSLASH",
  "SEMI",
  "EQUALS",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQR",
  "RSQR",
  "LCURLY",
  "RCURLY",
  "INCREMENT",
  "DECREMENT",
  "NOT",
  "QUESTION",
  "COLON",
  "GT",
  "LT",
  "LTE",
  "GTE",
  "EQ",
  "NEQ",
  "TRUE",
  "FALSE",
  "ID",
  "NUMBERLIT",
  "CHARLIT",
  "LETTER",
  "FLOATLIT",
  "STRING",
  "COMMENT",
  "MULTILINE"
  };
}

